apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-storage
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claims
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azure-disk-storage
  resources:
    requests:
      storage: 1Gi